spring:
  h2.console:
    enabled: true
    path: /h2-console

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test-db
      driver-class-name: org.h2.Driver
      username: sa
      password:
      connection-test-query: SELECT 1

  sql.init:
    encoding: UTF-8
    schema-locations: sql/schema.sql
    data-locations: sql/data.sql

mybatis:
  type-handlers-package: io.github.imsejin.study.mybatis.jdbc.mybatis

logging:
  level:
    org.springframework.batch: INFO
    io.github.imsejin.study.mybatis: DEBUG
